/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.haui.thangnd.XemKetQuaHocTap;

import com.haui.thaind.cache.UserManager;

import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 * @author TAVPLTNDTSUN
 */
public class XemDiemTongKet extends javax.swing.JPanel {
    ResultSet rs = null;
    Statement sta = null;
    Connect connect = new Connect();
    DefaultTableModel defaultTableModel;
    private static SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    private String MaSV;//Lấy Từ Login

    public String getMaSV() {
        return MaSV;
    }

    public void setMaSV(String maSV) {
        MaSV = maSV;
    }

    /**
     * Creates new form BXemDiemTongKet
     */
    public XemDiemTongKet() {
        initComponents();
        setMaSV(UserManager.instance().getUserName());
        loadLabel();
        loadTable();
    }

    public void loadTable() {
        try {
            connect.getConnect();
            jtb_DSDiemTongKet.removeAll();
            String[] name = {"STT", "Mã HP", "Mã MH", "Tên MH", "Giáo Viên", "Số TC", "Ngày BĐ", "Ngày KT", "Điểm H4", "Xếp Loại"};
            defaultTableModel = new DefaultTableModel(name, 0);
            jtb_DSDiemTongKet.setModel(defaultTableModel);
            String query = "select * from sinhvien sv inner join ketqua kq on sv.MASV = kq.MASV\n"
                    + "inner join hocphan hp on kq.MAHP = hp.MAHP\n"
                    + "inner join monhoc mh on hp.MAMH = mh.MAMH\n"
                    + "inner join giangvien gv on hp.MAGV = gv.MAGV\n"
                    + "Where sv.MASV = " + "'" + getMaSV() + "'";
            rs = connect.executeQuery(query);
            int sd = 1;
            while (rs.next()) {
                Vector v = new Vector();
                v.add(sd);
                v.add(rs.getString("MAHP"));
                v.add(rs.getString("MAMH"));
                v.add(rs.getString("TENMH"));
                v.add(rs.getString("TENGV"));
                v.add(rs.getInt("SOTINCHI"));
                v.add(getDay(rs.getLong("NGAYBD")));
                v.add(getDay(rs.getLong("NGAYKT")));
                v.add(rs.getFloat("DIEM"));
                v.add(getRanking(rs.getDouble("DIEM")));
                defaultTableModel.addRow(v);
                sd = sd + 1;
            }
            rs = null;
            jtb_DSDiemTongKet.setModel(defaultTableModel);
        } catch (Exception ex) {
            Logger.getLogger(XemDiemTongKet.class.getName()).log(Level.SEVERE, "Error", ex);
        }
    }

    public void loadLabel() {
        try {
            String query = "select * from sinhvien sv inner join LOP l on sv.MALOP = l.MALOP"
                    + " inner join GIANGVIEN gv on l.MAGV = gv.MAGV"
                    + " Where sv.MASV = '" + getMaSV() + "'";
            connect.getConnect();
            rs = connect.executeQuery(query);
            while (rs.next()) {
                jlb_maSinhVien.setText(rs.getString("MASV"));
                jlb_hoTen.setText(rs.getString("TENSV"));
                jlb_lop.setText(rs.getString("TENLOP"));
                jlb_giaoVienChuNhiem.setText(rs.getString("TENGV"));
            }
            rs = null;
        } catch (Exception ex) {
            Logger.getLogger(XemDiemTongKet.class.getName()).log(Level.SEVERE, "ERROR 1", ex);
        }
    }

    private static String getRanking(double point) {
        String result;
        if (point == 0.0) {
            return "";
        }
        if (point < 2.5) {
            result = "Trung Bình";
        } else if (point < 3.2) {
            result = "Khá";
        } else if (point < 3.5) {
            result = "Giỏi";
        } else {
            result = "Xuất Sắc";
        }
        return result;
    }

    private static String getDay(long day) {
        Date d;
        d = Date.from(Instant.ofEpochSecond(day));
        return sdf.format(d);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlb_maSinhVien = new javax.swing.JLabel();
        jlb_hoTen = new javax.swing.JLabel();
        jlb_lop = new javax.swing.JLabel();
        jlb_giaoVienChuNhiem = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_DSDiemTongKet = new javax.swing.JTable();

        setBackground(new java.awt.Color(240, 243, 215));

        jPanel1.setBackground(new java.awt.Color(240, 243, 215));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Xem Điểm Tổng Kết");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(481, 481, 481))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel1)
                                .addContainerGap(55, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(240, 243, 215));

        jLabel5.setText("Giáo Viên Chủ Nhiệm : ");

        jLabel4.setText("Lớp : ");

        jLabel3.setText("Họ Tên : ");

        jLabel2.setText("Mã Sinh Viên : ");

        jlb_maSinhVien.setText("jLabel6");

        jlb_hoTen.setText("jLabel7");

        jlb_lop.setText("jLabel8");

        jlb_giaoVienChuNhiem.setText("jLabel9");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                .addGap(405, 405, 405)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlb_giaoVienChuNhiem)
                                        .addComponent(jlb_lop)
                                        .addComponent(jlb_hoTen)
                                        .addComponent(jlb_maSinhVien))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jlb_maSinhVien))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(jlb_hoTen))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(jlb_lop))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(jlb_giaoVienChuNhiem))
                                .addContainerGap(54, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(240, 243, 215));

        jtb_DSDiemTongKet.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String[]{
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane1.setViewportView(jtb_DSDiemTongKet);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 11, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jlb_giaoVienChuNhiem;
    private javax.swing.JLabel jlb_hoTen;
    private javax.swing.JLabel jlb_lop;
    private javax.swing.JLabel jlb_maSinhVien;
    private javax.swing.JTable jtb_DSDiemTongKet;
    // End of variables declaration//GEN-END:variables
}
