/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.haui.thangnd.XemKetQuaHocTap;

import javax.swing.JPanel;

/**
 *
 * @author TAVPLTNDTSUN
 */
public class XemKetQuaHocTap extends javax.swing.JFrame {
    XemDiemTongKet xemDiemTongKet;
    XemDiemTrungBinhTichLuy xemDiemTrungBinhTichLuy;
    JPanel jPanelChild;
    /**
     * Creates new form XemKetQuaHocTap
     */
    public XemKetQuaHocTap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel_DSKetQuaHocTap = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jbtn_xemDiemTongKet = new javax.swing.JButton();
        jbtn_xemDiemTrungBinhTichLuy = new javax.swing.JButton();
        jbtn_troLai = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jmn_thoat = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmn_noiDung = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jmn_gioiThieu = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 204));
        jLabel1.setText("Xem Kết Quả Học Tập");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(512, 512, 512)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel_DSKetQuaHocTap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 204)));
        jPanel_DSKetQuaHocTap.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 204)));

        jbtn_xemDiemTongKet.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jbtn_xemDiemTongKet.setForeground(new java.awt.Color(255, 0, 204));
        jbtn_xemDiemTongKet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/haui/thangnd/XemKetQuaHocTap/Icon/arrow-32-32.png"))); // NOI18N
        jbtn_xemDiemTongKet.setText("                Xem Điểm Tổng Kết");
        jbtn_xemDiemTongKet.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtn_xemDiemTongKet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_xemDiemTongKetActionPerformed(evt);
            }
        });

        jbtn_xemDiemTrungBinhTichLuy.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jbtn_xemDiemTrungBinhTichLuy.setForeground(new java.awt.Color(255, 0, 204));
        jbtn_xemDiemTrungBinhTichLuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/haui/thangnd/XemKetQuaHocTap/Icon/arrow-32-32.png"))); // NOI18N
        jbtn_xemDiemTrungBinhTichLuy.setText("               Xem Điểm Trung Bình Tích Lũy");
        jbtn_xemDiemTrungBinhTichLuy.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtn_xemDiemTrungBinhTichLuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_xemDiemTrungBinhTichLuyActionPerformed(evt);
            }
        });

        jbtn_troLai.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jbtn_troLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/haui/thangnd/XemKetQuaHocTap/Icon/arrow-79-48.png"))); // NOI18N
        jbtn_troLai.setText("                Trở Lại");
        jbtn_troLai.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtn_troLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_troLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtn_xemDiemTrungBinhTichLuy, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                            .addComponent(jbtn_xemDiemTongKet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addComponent(jbtn_troLai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jbtn_xemDiemTongKet, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jbtn_xemDiemTrungBinhTichLuy, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 237, Short.MAX_VALUE)
                .addComponent(jbtn_troLai)
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 204, 204));

        jMenu1.setText("Hệ Thống");
        jMenu1.add(jSeparator2);

        jmn_thoat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        jmn_thoat.setText("Thoát");
        jmn_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmn_thoatActionPerformed(evt);
            }
        });
        jMenu1.add(jmn_thoat);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Hướng Dẫn");

        jmn_noiDung.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jmn_noiDung.setText("Nội Dung");
        jMenu3.add(jmn_noiDung);
        jMenu3.add(jSeparator3);

        jmn_gioiThieu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jmn_gioiThieu.setText("Giới Thiệu");
        jMenu3.add(jmn_gioiThieu);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel_DSKetQuaHocTap, javax.swing.GroupLayout.PREFERRED_SIZE, 1055, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_DSKetQuaHocTap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_xemDiemTongKetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_xemDiemTongKetActionPerformed
        // TODO add your handling code here:
        jPanel_DSKetQuaHocTap.removeAll();
        jPanelChild = new XemDiemTongKet();
        jPanel_DSKetQuaHocTap.add(jPanelChild);
        jPanel_DSKetQuaHocTap.validate();
    }//GEN-LAST:event_jbtn_xemDiemTongKetActionPerformed

    private void jbtn_xemDiemTrungBinhTichLuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_xemDiemTrungBinhTichLuyActionPerformed
        // TODO add your handling code here:
        jPanel_DSKetQuaHocTap.removeAll();
        jPanelChild = new XemDiemTrungBinhTichLuy();
        jPanel_DSKetQuaHocTap.add(jPanelChild);
        jPanel_DSKetQuaHocTap.validate();
    }//GEN-LAST:event_jbtn_xemDiemTrungBinhTichLuyActionPerformed

    private void jbtn_troLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_troLaiActionPerformed
        // TODO add your handling code here:
        //Write To Code Back
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jbtn_troLaiActionPerformed

    private void jmn_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmn_thoatActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jmn_thoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XemKetQuaHocTap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XemKetQuaHocTap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XemKetQuaHocTap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XemKetQuaHocTap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XemKetQuaHocTap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_DSKetQuaHocTap;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JButton jbtn_troLai;
    private javax.swing.JButton jbtn_xemDiemTongKet;
    private javax.swing.JButton jbtn_xemDiemTrungBinhTichLuy;
    private javax.swing.JMenuItem jmn_gioiThieu;
    private javax.swing.JMenuItem jmn_noiDung;
    private javax.swing.JMenuItem jmn_thoat;
    // End of variables declaration//GEN-END:variables
}
